
import { useEffect } from 'react'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useDispatch, useSelector } from 'react-redux'

import {allProductsSelector, getAllProduct} from '../redux'

export default function Home() {
  const dispatch = useDispatch()
  const products = useSelector(allProductsSelector)
  useEffect(()=>{
    if(products.length === 0){
      dispatch(getAllProduct())
    }
  },[])
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex container mx-auto px-6">
        <h1 className="text-3xl font-bold underline">Test</h1>
        <p className="hover:opacity-75 opacity-50 hover:scale-150 scale-125">
          Getting a new business off the ground is a lot of hard work.
          Here are five ideas you can use to find your first customers.
        </p>
      </main>
    </div>
  )
}